name: campus_app
description: Simplifie, improve and facilitate everyday students life.
publish_to: 'none'
version: 2.3.2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  envied: ^0.5.4+1
  flutter_native_splash: ^2.4.0
  flutter_html: ^3.0.0-alpha.5
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  xml: ^6.3.0
  animations: ^2.0.8
  page_transition: ^2.1.0
  cached_network_image: ^3.3.1
  cookie_jar: ^4.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  native_dio_adapter: ^1.3.0
  get_it: ^7.7.0
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  path_provider: ^2.1.2
  snapping_sheet_2: ^3.1.5
  flutter_displaymode: ^0.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  url_launcher: ^6.2.3 
  flutter_inappwebview: ^6.0.0
  firebase_core: ^2.32.0 
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2 
  share_plus: ^9.0.0
  uni_links: ^0.5.1
  flutter_onboarding:
    git:
      url: https://github.com/C4s4r/flutter_onboarding
      ref: 9d74464
  flutter_nfc_kit: ^3.5.2
  lottie: ^3.0.0
  screen_brightness: ^1.0.1
  fluttertoast: ^8.2.5
  appwrite: ^12.0.4
  slugid: ^1.1.2
  visibility_detector: ^0.4.0+2
  appinio_video_player: ^1.2.2
  sentry_flutter: ^8.2.0
  sentry: ^8.2.0
  video_thumbnail: ^0.5.3
  image: ^4.2.0
  dismissible_page: ^1.0.2

  location: ^5.0.3
  flutter_map: ^6.0.1
  flutter_polyline_points: ^2.0.0
  flutter_map_location_marker: any
  geolocator: ^10.1.0
  latlong2: ^0.9.0
  photo_view: ^0.14.0

  dijkstra: ^0.0.4         
  image_editor: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10 
  flutter_lints: ^4.0.0
  mockito: ^5.4.3
  envied_generator: ^0.5.3 
  flutter_launcher_icons: ^0.13.1

# Override js version as flutter_inappwebview depends on flutter_inappwebview_web which uses js version ^0.6.4 but as the web package is not used, this is risk-free
dependency_overrides:
  js: ^0.7.1

flutter_native_splash:
  image: "assets/img/Android-RUB_Campus_App_Logo.png"
  color: "#ffffff"
  image_dark: "assets/img/Android-RUB_Campus_App_Logo.png"
  color_dark: "#0e1420"
  branding_android: "assets/img/SplashScreen-AStA-branding.png"
  branding_dark_android: "assets/img/SplashScreen-AStA-branding-dark.png"
  branding_ios: "assets/img/SplashScreen-AStA-branding-ios.png"
  branding_dark_ios: "assets/img/SplashScreen-AStA-branding-dark-ios.png"
  # Android 12 handles the splash screen differently than previous versions
  android_12:
    image: "assets/img/SplashScreen-logo.png"
    color: "#ffffff"
    image_dark: "assets/img/SplashScreen-logo.png"
    color_dark: "#0e1420"
    icon_background_color_dark: "#0e1420"
    branding: "assets/img/SplashScreen-AStA-branding-android12.png"
    branding_dark: "assets/img/SplashScreen-AStA-branding-dark-android12.png"
  web: false

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/img/Android-RUB_Campus_App_Logo.png"
  image_path_ios: "assets/img/IOS-RUB_Campus_App_Logo.png"
  min_sdk_android: 21

flutter:
  assets:
     - assets/img/SplashScreen-logo.png
     - assets/img/SplashScreen-AStA-branding.png
     - assets/img/asta_logo.png
     - assets/img/mensa.png
     - assets/img/qwest.png
     - assets/img/rotebeete.png
     - assets/img/asta-gaming-hub.png
     - assets/img/icons/hochschulsport_icon.png
     - assets/img/icons/home-outlined.png
     - assets/img/icons/home-filled.png
     - assets/img/icons/calendar-outlined.png
     - assets/img/icons/calendar-filled.png
     - assets/img/icons/door-closed.svg
     - assets/img/icons/mensa-outlined.png
     - assets/img/icons/mensa-filled.png
     - assets/img/icons/help-outlined.png
     - assets/img/icons/help-filled.png
     - assets/img/icons/wallet-outlined.png
     - assets/img/icons/wallet-filled.png
     - assets/img/icons/vote.svg
     - assets/img/icons/error.svg
     - assets/img/icons/more.png
     - assets/img/icons/settings.svg
     - assets/img/icons/info.svg
     - assets/img/icons/instagram.svg
     - assets/img/icons/facebook.svg
     - assets/img/icons/twitch.svg
     - assets/img/icons/website.svg
     - assets/img/icons/mail.svg
     - assets/img/icons/search.svg
     - assets/img/icons/filter.svg
     - assets/img/icons/arrow-left.svg
     - assets/img/icons/arrow-right.svg
     - assets/img/icons/info-message.svg
     - assets/img/icons/x.svg
     - assets/img/icons/map-outlined.png
     - assets/img/icons/map-filled.png
     - assets/img/icons/mensa-alcohol.png
     - assets/img/icons/mensa-beef.png
     - assets/img/icons/mensa-chicken.png
     - assets/img/icons/mensa-fish.png
     - assets/img/icons/mensa-halal.png
     - assets/img/icons/mensa-lamm.png
     - assets/img/icons/mensa-pork.png
     - assets/img/icons/mensa-vegan.png
     - assets/img/icons/mensa-vegetarian.png
     - assets/img/icons/mensa-venison.png
     - assets/img/icons/chevron-right.svg
     - assets/img/icons/external-link.svg
     - assets/img/icons/mail-link.png
     - assets/img/icons/moodle-link.png
     - assets/img/icons/flexnow-link.png
     - assets/img/icons/rub-link.png
     - assets/img/icons/siren.svg
     - assets/img/icons/message-square.svg
     - assets/img/icons/share.svg
     - assets/img/icons/discord-filled.svg
     - assets/img/icons/github.svg
     - assets/img/icons/help-circle.svg
     - assets/img/icons/euro.svg
     - assets/animations/nfc-light.json
     - assets/animations/nfc-dark.json
     - assets/animations/coin-flip.json
     - assets/img/bogestra-logo.svg
     - assets/img/icons/file-plus.svg
     - lib/pages/pathfinder/maps/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900

  uses-material-design: true
  generate: true