name: campus_app
description: Simplifie, improve and facilitate everyday students life.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_secure_storage: ^6.0.0
  provider: ^6.0.3
  flutter_svg: ^1.1.4
  page_transition: ^2.0.9
  cached_network_image: ^3.2.1
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  get_it: ^7.2.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.11
  pdfx: ^2.0.1+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8  
  flutter_lints: ^1.0.0
  mockito: ^5.1.0

flutter:
  assets:
     - assets/img/icons/home-outlined.png
     - assets/img/icons/home-filled.png
     - assets/img/icons/calendar-outlined.png
     - assets/img/icons/calendar-filled.png
     - assets/img/icons/mensa-outlined.png
     - assets/img/icons/mensa-filled.png
     - assets/img/icons/help-outlined.png
     - assets/img/icons/help-filled.png
     - assets/img/icons/more.png
     - assets/documents/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
  #  - family: CircularStd
  #    fonts:
  #      - asset: assets/fonts/CircularStd-Medium.otf
  #      - asset: assets/fonts/CircularStd-Book.otf
  #        weight: 600
  #      - asset: assets/fonts/CircularStd-Bold.otf
  #        weight: 700
  #      - asset: assets/fonts/CircularStd-Black.otf
  #        weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  uses-material-design: true
  generate: true
